[context.split1.environment]
HUGO_VERSION = "0.60.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.60"

[context.production.environment]
HUGO_VERSION = "0.60"

[context.branch-deploy.environment]
HUGO_VERSION = "0.60.0"
