context.split1.environment]
HUGO_VERSION = "0.58.0"

[context.deploy-preview.environment]
HUGO_VERSION = "0.58.0"

[context.production.environment]
HUGO_VERSION = "0.58.0"

[context.branch-deploy.environment]
HUGO_VERSION = "0.58.0"
